version: '3.7'

volumes:
    logs:
        driver: local

services:
    slim:
        image: php:8.1-alpine
        working_dir: /var/www
        command: php -S 0.0.0.0:8080 -t public
        environment:
            docker: "true"
        ports:
            - "8080:8080"
        volumes:
            - .:/var/www
            - logs:/var/www/logs
        depends_on:
            -   db
    db:
        image: mysql:8
        restart: always
        ports:
            - "3306:3306"
        environment:
            MYSQL_DATABASE: running-shoes
            MYSQL_ROOT_PASSWORD: running-shoes
